/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishing.simm;

/**
 *
 * @author William
 */
public class Start_window extends javax.swing.JFrame {

    /**
     * Creates new form Start_window
     */
    public Start_window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        about_b = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        stats_b = new javax.swing.JButton();
        exit_b = new javax.swing.JButton();
        shop_b = new javax.swing.JButton();
        fish_b = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36));
        jLabel1.setText("Fishing Simulator");

        about_b.setFont(new java.awt.Font("Impact", 2, 14));
        about_b.setForeground(new java.awt.Color(0, 102, 102));
        about_b.setText("Guide");
        about_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_bActionPerformed(evt);
            }
        });

        stats_b.setFont(new java.awt.Font("Impact", 0, 14));
        stats_b.setForeground(new java.awt.Color(204, 204, 0));
        stats_b.setText("Stats");
        stats_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stats_bActionPerformed(evt);
            }
        });

        exit_b.setFont(new java.awt.Font("Impact", 0, 14));
        exit_b.setForeground(new java.awt.Color(255, 0, 0));
        exit_b.setText("Exit");

        shop_b.setFont(new java.awt.Font("Impact", 0, 14));
        shop_b.setForeground(new java.awt.Color(51, 255, 0));
        shop_b.setText("Shop");
        shop_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop_bActionPerformed(evt);
            }
        });

        fish_b.setFont(new java.awt.Font("Impact", 0, 14));
        fish_b.setForeground(new java.awt.Color(255, 102, 51));
        fish_b.setText("FISH");
        fish_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fish_bActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("H:\\ICS3U\\logo.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(about_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stats_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fish_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shop_b)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(exit_b))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shop_b)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fish_b)
                        .addComponent(about_b)
                        .addComponent(stats_b)
                        .addComponent(exit_b)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void about_bActionPerformed(java.awt.event.ActionEvent evt) {                                        
About_window about_win;
        about_win = new About_window();
        about_win.setVisible(true);
    }                                       

    private void stats_bActionPerformed(java.awt.event.ActionEvent evt) {                                        
Stat_window stat_win=new Stat_window();
stat_win.setVisible(true);
    }                                       

    private void fish_bActionPerformed(java.awt.event.ActionEvent evt) {                                       
Fish_window fish_win = new Fish_window();
fish_win.setVisible(true);
    }                                      

    private void shop_bActionPerformed(java.awt.event.ActionEvent evt) {                                       
Shop_window shop_win=new Shop_window();
shop_win.setVisible(true);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
   
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton about_b;
    private javax.swing.JButton exit_b;
    private javax.swing.JButton fish_b;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton shop_b;
    private javax.swing.JButton stats_b;
    // End of variables declaration                   
}
